# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - releases/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.13.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get -y update && sudo apt-get -y install libxtst-dev libpng++-dev sox fakeroot
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Get dependancies for Linux'

- task: CacheBeta@0
  inputs:
    key: yarn | $(Agent.OS) | yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- script: yarn --frozen-lockfile

- script: |
    yarn make
  displayName: 'Make the binaries'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'natter_$(Agent.OS)_build'
    targetPath: 'out/make'
  displayName: 'Publish $(Agent.OS) outputs'
