# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.13.x'
  displayName: 'Install Node.js'

# Linux
- script: |
    sudo apt-get -y update && sudo apt-get -y install libxtst-dev libpng++-dev sox fakeroot
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Get dependancies for Linux'

- script: |
    npm install
  displayName: 'Install all NPM packages'

- script: |
    npm run make
  displayName: 'Make the binaries'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'natter_linux_build'
    targetPath: 'out/make'
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Copy outputs for Linux'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'natter_mac_build'
    targetPath: 'out/make'
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: 'Copy outputs for Mac'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'natter_windows_build'
    targetPath: 'out/make'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Copy outputs for Windows'
